project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  eval: true
  echo: true
  warning: true
  message: false
  cache: true

jupyter: julia-1.10

book:
  title: "Tidier Data Science with Julia"
  author: "Guilherme Vituri and Christoph Scheuch"
  date: "15/08/2024"
  reader-mode: true
  
  chapters:
    - index.qmd
    - part: "Part 1: Julia basics"
      chapters: 
      - dataframes.qmd
    - part: "Part 2: Manipulating data"
    - part: "Part 3: Reading data"
    - part: "Part 4: Plotting data"
    - part: "Part 5: Applications"
      chapters:
        - references.qmd
      # - introduction.qmd
    # - data-visualization.qmd
    # - workflow-basics.qmd
    # - data-transformation.qmd
    # - workflow-code-style.qmd
    # - data-tidying.qmd
    # - workflow-scripts-and-projects.qmd
    # - data-import.qmd
    # - workflow-getting-help.qmd

bibliography: references.bib
biblio-style: apalike
link-citations: true
links-as-notes: true

format:
  html:
    theme: cosmo
    codee-link: true
    callout-appearance: simple
